/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Resource,
  Alternative,
  GraphNode,
  GraphEdge,
  Workload,
  SchedulerDecision,
  RuntimeEvent,
  SystemSettings,
} from '../types';

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'resource-api-gateway',
    name: 'resource-api-gateway',
    type: 'Ingress Proxy',
    category: 'ingress',
    status: 'healthy',
    runtime: 'Envoy v1.28.4',
    endpoint: 'gw-ingress.prod.internal:443',
    namespace: 'ingress-prod',
    protocols: ['HTTP/2', 'gRPC', 'TLSv1.3'],
    dependencies: ['resource-auth', 'resource-worker'],
    dependents: ['external-clients'],
    alternatives: ['res-alt-gw-02'],
    upstreamInflow: '18,412 req/sec',
    upstreamClients: ['Cloudflare Edge CDN', 'Partner gRPC Clients', 'Mobile Gateway'],
    downstreamDeps: [
      { name: 'resource-auth', target: 'auth-svc.prod:8443', role: 'Token Verification', status: 'healthy' },
      { name: 'resource-worker', target: 'worker-fleet.prod:9090', role: 'Compute Core', status: 'healthy' },
    ],
    uptime: '42d 18h 12m',
    lastUpdated: 'Just now',
    metrics: {
      cpu: 42,
      memory: '3.8 GB',
      p99Latency: '14.2ms',
      replicas: '12 / 12',
      errorRate: '0.004%',
      conns: 8420,
      qps: '18.4k',
    },
  },
  {
    id: 'resource-auth',
    name: 'resource-auth',
    type: 'Security Service',
    category: 'service',
    status: 'healthy',
    runtime: 'Go 1.22 / SPIFFE-SPIRE',
    endpoint: 'auth-svc.prod.internal:8443',
    namespace: 'security-prod',
    protocols: ['gRPC', 'mTLS'],
    dependencies: ['resource-redis', 'resource-postgres'],
    dependents: ['resource-api-gateway', 'resource-worker'],
    alternatives: ['res-alt-auth-backup'],
    upstreamInflow: '12,940 req/sec',
    upstreamClients: ['resource-api-gateway'],
    downstreamDeps: [
      { name: 'resource-redis', target: 'redis-cluster.prod:6379', role: 'Session Store', status: 'healthy' },
      { name: 'resource-postgres', target: 'pg-primary.prod:5432', role: 'User Credentials', status: 'healthy' },
    ],
    uptime: '19d 04h 55m',
    lastUpdated: '1m ago',
    metrics: {
      cpu: 28,
      memory: '1.2 GB',
      p99Latency: '4.8ms',
      replicas: '8 / 8',
      errorRate: '0.001%',
      conns: 1200,
      qps: '12.9k',
    },
  },
  {
    id: 'resource-worker',
    name: 'resource-worker',
    type: 'Compute Fleet',
    category: 'compute',
    status: 'healthy',
    runtime: 'K8s v1.28.4 (48 nodes)',
    endpoint: 'worker-fleet.prod.internal:9090',
    namespace: 'compute-prod',
    protocols: ['gRPC', 'Internal Wire v3'],
    dependencies: ['resource-redis', 'resource-postgres', 'resource-queue', 'resource-storage'],
    dependents: ['resource-api-gateway'],
    alternatives: ['res-alt-worker-backup'],
    upstreamInflow: '6,480 jobs/sec',
    upstreamClients: ['resource-api-gateway'],
    downstreamDeps: [
      { name: 'resource-redis', target: 'redis-cluster.prod:6379', role: 'Task Cache', status: 'healthy' },
      { name: 'resource-postgres', target: 'pg-primary.prod:5432', role: 'State Record', status: 'healthy' },
      { name: 'resource-queue', target: 'kafka-broker.prod:9092', role: 'Event Pipeline', status: 'healthy' },
    ],
    uptime: '8d 14h 02m',
    lastUpdated: 'Just now',
    metrics: {
      cpu: 64,
      memory: '28.4 GB',
      p99Latency: '32.1ms',
      replicas: '48 / 48',
      errorRate: '0.012%',
      conns: 4190,
      qps: '6.4k',
    },
  },
  {
    id: 'resource-redis',
    name: 'resource-redis',
    type: 'In-Memory Store',
    category: 'cache',
    status: 'healthy',
    runtime: 'Redis Cluster v7.2.3',
    endpoint: 'redis-cluster.prod.internal:6379',
    namespace: 'data-prod',
    protocols: ['RESP3'],
    dependencies: [],
    dependents: ['resource-auth', 'resource-worker'],
    alternatives: ['res-alt-cache-memcached'],
    upstreamInflow: '42,100 ops/sec',
    upstreamClients: ['resource-auth', 'resource-worker'],
    uptime: '99d 02h 11m',
    lastUpdated: '10s ago',
    metrics: {
      cpu: 18,
      memory: '14.1 GB / 32 GB',
      p99Latency: '0.9ms',
      replicas: '6 shards (12 nodes)',
      errorRate: '0.000%',
      conns: 980,
      qps: '42.1k',
    },
  },
  {
    id: 'resource-postgres',
    name: 'resource-postgres',
    type: 'Relational DB',
    category: 'db',
    status: 'healthy',
    runtime: 'Aurora PostgreSQL 16.1',
    endpoint: 'pg-primary.prod.internal:5432',
    namespace: 'data-prod',
    protocols: ['Postgres Wire v3'],
    dependencies: ['resource-storage'],
    dependents: ['resource-auth', 'resource-worker'],
    alternatives: ['res-alt-db-replica'],
    upstreamInflow: '3,840 queries/sec',
    upstreamClients: ['resource-auth', 'resource-worker'],
    uptime: '124d 11h',
    lastUpdated: '2s ago',
    metrics: {
      cpu: 51,
      memory: '48.2 GB / 64 GB',
      p99Latency: '18.4ms',
      replicas: '1 Master, 3 Replicas',
      errorRate: '0.002%',
      conns: 310,
      qps: '3.8k',
    },
  },
  {
    id: 'resource-queue',
    name: 'resource-queue',
    type: 'Message Queue',
    category: 'queue',
    status: 'healthy',
    runtime: 'Apache Kafka 3.6 / KRaft',
    endpoint: 'kafka-broker.prod.internal:9092',
    namespace: 'stream-prod',
    protocols: ['Kafka Protocol v12'],
    dependencies: ['resource-storage'],
    dependents: ['resource-worker'],
    alternatives: ['res-alt-queue-rabbit'],
    upstreamInflow: '9,200 msg/sec',
    upstreamClients: ['resource-worker'],
    uptime: '38d 09h',
    lastUpdated: 'Just now',
    metrics: {
      cpu: 34,
      memory: '18.6 GB',
      p99Latency: '5.2ms',
      replicas: '5 Brokers',
      errorRate: '0.000%',
      conns: 640,
      qps: '9.2k',
    },
  },
  {
    id: 'resource-storage',
    name: 'resource-storage',
    type: 'Distributed Object Store',
    category: 'storage',
    status: 'healthy',
    runtime: 'Ceph / S3 API Compatible',
    endpoint: 's3-cluster.prod.internal:9000',
    namespace: 'storage-prod',
    protocols: ['Amazon S3 API', 'HTTPS'],
    dependencies: [],
    dependents: ['resource-postgres', 'resource-worker', 'resource-queue'],
    alternatives: ['res-alt-storage-cold'],
    upstreamInflow: '1,120 IOPS',
    upstreamClients: ['resource-postgres', 'resource-worker', 'resource-queue'],
    uptime: '180d 05h',
    lastUpdated: '3m ago',
    metrics: {
      cpu: 22,
      memory: '32.0 GB',
      p99Latency: '24.8ms',
      replicas: '8 OSD Nodes (RAID-Z)',
      errorRate: '0.000%',
      conns: 180,
      qps: '1.1k',
    },
  },
  {
    id: 'res-alt-gw-02',
    name: 'res-alt-gw-02 (Failover Gateway)',
    type: 'Ingress Proxy',
    category: 'ingress',
    status: 'running',
    runtime: 'Envoy v1.28.4 (Hot-Standby)',
    endpoint: 'gw-failover-b.prod.internal:443',
    namespace: 'ingress-prod',
    protocols: ['HTTP/2', 'gRPC'],
    dependencies: ['resource-auth', 'resource-worker'],
    dependents: [],
    alternatives: [],
    upstreamInflow: '0 req/sec (Warm Standby)',
    uptime: '42d 18h',
    lastUpdated: 'Just now',
    metrics: {
      cpu: 4,
      memory: '1.1 GB',
      p99Latency: '11.8ms',
      replicas: '6 / 6',
      errorRate: '0.000%',
      conns: 12,
      qps: '0',
    },
  },
];

export const INITIAL_ALTERNATIVES: Alternative[] = [
  {
    id: 'res-alt-gw-02',
    name: 'res-alt-gw-02 (Failover-Envoy-B)',
    primaryResourceId: 'resource-api-gateway',
    primaryResourceName: 'resource-api-gateway',
    primaryEndpoint: 'gw-ingress.prod.internal:443',
    fallbackEndpoint: 'gw-failover-b.prod.internal:443',
    tier: 'Tier-1',
    substitutionType: 'Seamless Dual-Route Failover',
    status: 'available',
    trafficDiverted: 0,
    trafficVolume: '0 req/sec (Standby)',
    compatibility: 100,
    syncLag: '0.0 ms',
    lastHealthCheck: '2.4s ago',
    readinessSla: '< 100ms switchover',
    zone: 'us-east-1b (Isolated AZ)',
    hardwareMatch: 'Identical (16 vCPU, 32GB RAM)',
    runtimeDaemon: 'Envoy DaemonSet v1.28.4',
    affinityHost: 'node-pool-ingress-b',
    livenessStatus: 'Passing (HTTP 200 /readyz)',
    readinessStatus: '100% Ready',
    canaryStatus: 'Validated in Stage 4',
    p95p99Latency: '8.4ms / 14.1ms',
    triggerCondition: 'Primary Gateway 3x consecutive health probe timeouts or error rate > 2.5%',
  },
  {
    id: 'res-alt-db-replica',
    name: 'res-alt-db-replica (Aurora Replica 01)',
    primaryResourceId: 'resource-postgres',
    primaryResourceName: 'resource-postgres',
    primaryEndpoint: 'pg-primary.prod.internal:5432',
    fallbackEndpoint: 'pg-replica-01.prod.internal:5432',
    tier: 'Tier-1',
    substitutionType: 'Read/Write Promotion on Quorum Loss',
    status: 'active_fallback',
    trafficDiverted: 35,
    trafficVolume: '1,340 read queries/sec',
    compatibility: 100,
    syncLag: '0.4 ms',
    lastHealthCheck: '1.1s ago',
    readinessSla: '< 2.5s master promotion',
    zone: 'us-east-1c',
    hardwareMatch: 'Identical (r6g.4xlarge Aurora)',
    runtimeDaemon: 'Aurora Storage Engine v3.04',
    affinityHost: 'db-replica-cluster-c',
    livenessStatus: 'Passing (Streaming replication active)',
    readinessStatus: 'Standby / Read Active',
    canaryStatus: 'Quorum sync verified',
    p95p99Latency: '12.0ms / 19.5ms',
    triggerCondition: 'Primary Postgres failover signal, heartbeat silent > 5000ms',
  },
  {
    id: 'res-alt-worker-backup',
    name: 'res-alt-worker-backup (Secondary Worker Fleet)',
    primaryResourceId: 'resource-worker',
    primaryResourceName: 'resource-worker',
    primaryEndpoint: 'worker-fleet.prod.internal:9090',
    fallbackEndpoint: 'worker-backup.prod.internal:9090',
    tier: 'Tier-2',
    substitutionType: 'Overflow Burst & Degraded Mode',
    status: 'available',
    trafficDiverted: 0,
    trafficVolume: '0 jobs/sec',
    compatibility: 98,
    syncLag: '1.2 ms',
    lastHealthCheck: '4.8s ago',
    readinessSla: '< 15s cold scale',
    zone: 'us-east-1a / us-east-1b',
    hardwareMatch: 'Spot Instances (c6g.2xlarge)',
    runtimeDaemon: 'K8s Node Autoscaler',
    affinityHost: 'spot-worker-pool-02',
    livenessStatus: 'Passing (Heartbeat OK)',
    readinessStatus: 'Scaled to 8 standby pods',
    canaryStatus: 'Warm pre-baked images',
    p95p99Latency: '35.0ms / 48.0ms',
    triggerCondition: 'Queue depth > 10,000 tasks or primary CPU saturation > 85%',
  },
  {
    id: 'res-alt-cache-memcached',
    name: 'res-alt-cache-memcached (Memcached Ephemeral Fallback)',
    primaryResourceId: 'resource-redis',
    primaryResourceName: 'resource-redis',
    primaryEndpoint: 'redis-cluster.prod.internal:6379',
    fallbackEndpoint: 'memcached-aux.prod.internal:11211',
    tier: 'Tier-3',
    substitutionType: 'Degraded Key-Value Read-Through',
    status: 'standby',
    trafficDiverted: 0,
    trafficVolume: '0 ops/sec',
    compatibility: 85,
    syncLag: 'N/A (Cold Cache)',
    lastHealthCheck: '12s ago',
    readinessSla: '< 500ms client reroute',
    zone: 'us-east-1b',
    hardwareMatch: 'Memory optimized (r6g.large)',
    runtimeDaemon: 'Memcached v1.6.22',
    affinityHost: 'memcached-aux-pool',
    livenessStatus: 'Passing (TCP Echo OK)',
    readinessStatus: 'Standby',
    canaryStatus: 'Compatible GET/SET subset',
    p95p99Latency: '1.2ms / 2.8ms',
    triggerCondition: 'Redis cluster split-brain or total OOM eviction cascade',
  },
];

export const INITIAL_GRAPH_NODES: GraphNode[] = [
  {
    id: 'gw-ingress',
    resourceId: 'resource-api-gateway',
    label: 'resource-api-gateway',
    subtitle: 'Envoy Ingress Proxy',
    type: 'Ingress Proxy',
    status: 'healthy',
    x: 80,
    y: 190,
    metrics: { p99: '14ms', cpu: '42%', conns: 8420, replicas: '12/12' },
  },
  {
    id: 'gw-standby',
    resourceId: 'res-alt-gw-02',
    label: 'res-alt-gw-02',
    subtitle: 'Failover Gateway (Hot-Standby)',
    type: 'Ingress Proxy',
    status: 'standby',
    isStandby: true,
    x: 80,
    y: 350,
    metrics: { p99: '11ms', conns: 12, replicas: '6/6', weight: 'Standby' },
  },
  {
    id: 'svc-auth',
    resourceId: 'resource-auth',
    label: 'resource-auth',
    subtitle: 'SPIFFE Token Auth',
    type: 'Security Service',
    status: 'healthy',
    x: 350,
    y: 110,
    metrics: { p99: '4.8ms', cpu: '28%', replicas: '8/8' },
  },
  {
    id: 'svc-worker',
    resourceId: 'resource-worker',
    label: 'resource-worker',
    subtitle: 'K8s Compute Fleet',
    type: 'Compute Fleet',
    status: 'healthy',
    x: 350,
    y: 270,
    metrics: { p99: '32ms', cpu: '64%', replicas: '48/48' },
  },
  {
    id: 'cache-redis',
    resourceId: 'resource-redis',
    label: 'resource-redis',
    subtitle: 'Cluster v7.2 (6 Shards)',
    type: 'In-Memory Store',
    status: 'healthy',
    x: 630,
    y: 90,
    metrics: { p99: '0.9ms', hit: '99.8%', mem: '14.1GB' },
  },
  {
    id: 'db-postgres',
    resourceId: 'resource-postgres',
    label: 'resource-postgres',
    subtitle: 'Aurora PG 16 Primary',
    type: 'Relational DB',
    status: 'healthy',
    x: 630,
    y: 230,
    metrics: { p99: '18ms', conns: 310, io: '3.8k qps' },
  },
  {
    id: 'mq-queue',
    resourceId: 'resource-queue',
    label: 'resource-queue',
    subtitle: 'Kafka KRaft Cluster',
    type: 'Message Queue',
    status: 'healthy',
    x: 630,
    y: 370,
    metrics: { p99: '5.2ms', lag: '12ms', jobs: '9.2k/s' },
  },
  {
    id: 'storage-s3',
    resourceId: 'resource-storage',
    label: 'resource-storage',
    subtitle: 'Ceph S3 Storage Pool',
    type: 'Distributed Object Store',
    status: 'healthy',
    x: 900,
    y: 270,
    metrics: { p99: '24ms', io: '1.1k IOPS', vol: '148TB' },
  },
];

export const INITIAL_GRAPH_EDGES: GraphEdge[] = [
  { id: 'e1', source: 'gw-ingress', target: 'svc-auth', type: 'in_band', animated: true, label: 'gRPC / TLS' },
  { id: 'e2', source: 'gw-ingress', target: 'svc-worker', type: 'in_band', animated: true, label: 'Wire v3' },
  { id: 'e3', source: 'gw-standby', target: 'svc-auth', type: 'fallback', label: 'Failover Link' },
  { id: 'e4', source: 'gw-standby', target: 'svc-worker', type: 'fallback', label: 'Failover Link' },
  { id: 'e5', source: 'svc-auth', target: 'cache-redis', type: 'in_band', animated: true, label: 'RESP3' },
  { id: 'e6', source: 'svc-auth', target: 'db-postgres', type: 'in_band', animated: true, label: 'PG Wire' },
  { id: 'e7', source: 'svc-worker', target: 'cache-redis', type: 'in_band', animated: true, label: 'Read/Write' },
  { id: 'e8', source: 'svc-worker', target: 'db-postgres', type: 'in_band', animated: true, label: 'Tx State' },
  { id: 'e9', source: 'svc-worker', target: 'mq-queue', type: 'in_band', animated: true, label: 'Pub/Sub' },
  { id: 'e10', source: 'db-postgres', target: 'storage-s3', type: 'sync', label: 'WAL Backup' },
  { id: 'e11', source: 'mq-queue', target: 'storage-s3', type: 'sync', label: 'Tiered Log' },
];

export const INITIAL_WORKLOADS: Workload[] = [
  {
    id: 'wl-auth-902',
    name: 'Batch Session Invalidation',
    targetResourceId: 'resource-auth',
    targetResourceName: 'resource-auth',
    targetEndpoint: 'auth-svc.prod.internal:8443',
    status: 'running',
    started: '1m 24s ago',
    duration: '1m 24s',
    estimatedRemaining: '45s',
    progress: 68,
    schedulerDecision: 'Primary Node Preferred (Affinity: Security Pool)',
    selectedResource: 'resource-auth (Node-04)',
    alternativesEvaluated: [
      { name: 'resource-auth (Node-04)', score: 98, note: 'Lowest CPU (22%), warm memory cache', status: 'ready' },
      { name: 'res-alt-auth-backup', score: 72, note: 'Standby node, cold caches', status: 'reserve' },
    ],
    eventTrace: [
      { time: '10:44:12', message: 'Workload enqueued in scheduler queue', type: 'info' },
      { time: '10:44:13', message: 'Scheduler evaluated 2 viable execution targets', type: 'info' },
      { time: '10:44:14', message: 'Assigned to resource-auth via affinity rule', type: 'success' },
      { time: '10:44:15', message: 'Processing 42,000 session revocation tokens', type: 'info' },
    ],
  },
  {
    id: 'wl-comp-411',
    name: 'Telemetry Aggregation Engine',
    targetResourceId: 'resource-worker',
    targetResourceName: 'resource-worker',
    targetEndpoint: 'worker-fleet.prod.internal:9090',
    status: 'running',
    started: '14m 10s ago',
    duration: '14m 10s',
    progress: 88,
    schedulerDecision: 'Distributed Partitioning (Parallel Rank: 16)',
    selectedResource: 'resource-worker (48 pods)',
    alternativesEvaluated: [
      { name: 'resource-worker', score: 95, note: '48 pods active, optimal IO distribution', status: 'ready' },
      { name: 'res-alt-worker-backup', score: 50, note: 'Scale cold, would require 15s delay', status: 'ineligible' },
    ],
    eventTrace: [
      { time: '10:31:00', message: 'Triggered by cron timer (every 15m)', type: 'info' },
      { time: '10:31:02', message: 'Assigned 16 partitions to worker pool', type: 'success' },
    ],
  },
  {
    id: 'wl-db-sync-108',
    name: 'Aurora WAL Archival Pipeline',
    targetResourceId: 'resource-postgres',
    targetResourceName: 'resource-postgres',
    targetEndpoint: 'pg-primary.prod.internal:5432',
    status: 'queued',
    started: 'Queued',
    duration: 'Pending',
    progress: 0,
    schedulerDecision: 'Awaiting Storage I/O window (< 2000 IOPS)',
    selectedResource: 'Pending assignment',
    alternativesEvaluated: [
      { name: 'resource-postgres', score: 85, note: 'Master replication stream ready', status: 'ready' },
      { name: 'res-alt-db-replica', score: 92, note: 'Secondary replica candidate for offload', status: 'ready' },
    ],
    eventTrace: [
      { time: '10:45:00', message: 'Queued by WAL daemon', type: 'info' },
    ],
  },
  {
    id: 'wl-ing-test-09',
    name: 'Canary Synthetic Traffic Probing',
    targetResourceId: 'resource-api-gateway',
    targetResourceName: 'resource-api-gateway',
    targetEndpoint: 'gw-ingress.prod.internal:443',
    status: 'completed',
    started: '5m ago',
    duration: '3m 12s',
    progress: 100,
    schedulerDecision: 'Route 100 req/sec across primary & failover Envoy nodes',
    selectedResource: 'resource-api-gateway + res-alt-gw-02',
    alternativesEvaluated: [
      { name: 'resource-api-gateway', score: 100, note: '100% pass (HTTP 200, latency 12ms)', status: 'ready' },
      { name: 'res-alt-gw-02', score: 100, note: '100% pass (HTTP 200, latency 10ms)', status: 'ready' },
    ],
    eventTrace: [
      { time: '10:40:00', message: 'Synthetic canary pulse initiated', type: 'info' },
      { time: '10:43:12', message: 'Sweep completed: 0 errors detected across 18,000 probes', type: 'success' },
    ],
  },
];

export const INITIAL_SCHEDULER_DECISIONS: SchedulerDecision[] = [
  {
    id: 'dec-01',
    title: 'Workload #902 Assigned to resource-auth',
    workloadId: 'wl-auth-902',
    targetNode: 'resource-auth (Node-04)',
    description: 'Selected primary auth service instance based on local token cache affinity and lowest P99 latency (4.8ms).',
    timeAgo: '1m ago',
    type: 'worker',
  },
  {
    id: 'dec-02',
    title: 'Read Traffic Diverted to res-alt-db-replica',
    workloadId: 'wl-db-sync-108',
    targetNode: 'res-alt-db-replica (Aurora-01)',
    description: 'Split 35% read query stream to read replica after primary Postgres hit 51% CPU ceiling.',
    timeAgo: '4m ago',
    type: 'replica',
  },
  {
    id: 'dec-03',
    title: 'Warm Standby Confirmed for res-alt-gw-02',
    workloadId: 'wl-ing-test-09',
    targetNode: 'res-alt-gw-02 (AZ-B)',
    description: 'Health probes verified 100% readiness SLA (<100ms cutover). Keeping in zero-traffic hot standby.',
    timeAgo: '9m ago',
    type: 'backup',
  },
  {
    id: 'dec-04',
    title: 'Retried Job Partition #14 on Worker Node-12',
    workloadId: 'wl-comp-411',
    targetNode: 'resource-worker (Pod-12)',
    description: 'Transient socket timeout resolved on secondary retry attempt without invoking degraded fallback mode.',
    timeAgo: '16m ago',
    type: 'retry',
  },
];

export const INITIAL_RUNTIME_EVENTS: RuntimeEvent[] = [
  {
    id: 'evt-1049',
    timestamp: '2026-09-21 10:45:22 UTC',
    relativeTime: '2m ago',
    severity: 'info',
    type: 'Scheduling Decision',
    resource: 'resource-auth',
    resourceId: 'resource-auth',
    description: 'Scheduled batch session invalidation workload wl-auth-902 onto node-04 with cache affinity.',
    chips: [
      { label: 'WORKLOAD', value: 'wl-auth-902' },
      { label: 'TARGET', value: 'resource-auth' },
      { label: 'SCORE', value: '98/100' },
    ],
    details: {
      strategy: 'Affinity-First Round Robin',
      weight: 98,
      namespace: 'security-prod',
      host: 'node-pool-sec-04',
      latency: '4.8ms',
    },
    rawJson: {
      eventId: 'evt-1049',
      workload: 'wl-auth-902',
      scheduler: 'k8s-runtime-graph-scheduler',
      selectedNode: 'resource-auth',
      scores: { 'resource-auth': 98, 'res-alt-auth-backup': 72 },
    },
  },
  {
    id: 'evt-1048',
    timestamp: '2026-09-21 10:43:12 UTC',
    relativeTime: '4m ago',
    severity: 'success',
    type: 'Alternative Selected',
    resource: 'res-alt-db-replica',
    resourceId: 'res-alt-db-replica',
    description: 'Diverted 35% of analytics read queries to alternative resource res-alt-db-replica to protect primary DB headroom.',
    chips: [
      { label: 'ALTERNATIVE', value: 'res-alt-db-replica' },
      { label: 'TRAFFIC', value: '35% DIVERTED' },
      { label: 'LAG', value: '0.4ms' },
    ],
    details: {
      trigger: 'CPU Threshold > 50% on resource-postgres',
      scope: 'Read-Only Select Queries',
      nodesInSync: '3 of 3',
      replicationOffset: 142,
      reroute: '35% -> pg-replica-01.prod.internal:5432',
    },
    stateTransition: {
      from: 'PRIMARY: resource-postgres (100% Load)',
      fromDetail: 'CPU 51%, Read Queue Spiking',
      to: 'SPLIT: res-alt-db-replica (35% Read Traffic)',
      toDetail: 'Latency stable at 12ms P95',
      action: 'Automated Traffic Diverter Rule #T1-DB',
      latency: '0.4ms lag',
    },
    rootCauseAnalysis: 'Spike in analytics export queries during morning burst. Alternative read replica engaged seamlessly without query failures.',
    rawJson: {
      eventId: 'evt-1048',
      type: 'TRAFFIC_DIVERT',
      source: 'resource-postgres',
      target: 'res-alt-db-replica',
      divertRatio: 0.35,
      syncLagMs: 0.4,
    },
  },
  {
    id: 'evt-1047',
    timestamp: '2026-09-21 10:38:05 UTC',
    relativeTime: '9m ago',
    severity: 'warning',
    type: 'Dependency Failure',
    resource: 'resource-worker',
    resourceId: 'resource-worker',
    description: 'Transient gRPC transport timeout encountered while streaming partition 14 to Kafka broker #02.',
    chips: [
      { label: 'ERROR', value: 'DEADLINE_EXCEEDED', isError: true },
      { label: 'RETRIES', value: '1 / 3' },
      { label: 'SEVERITY', value: 'WARNING' },
    ],
    details: {
      trigger: 'Socket keepalive timeout on TCP connection 10.0.4.12:9092',
      grpcStatus: 'DEADLINE_EXCEEDED (code 4)',
      attempt: 'Retry 1 of 3 dispatched to broker #03',
      host: 'worker-fleet-pod-14',
    },
    rawJson: {
      eventId: 'evt-1047',
      error: 'transport endpoint timeout',
      target: 'kafka-broker-02',
      duration: '5002ms',
    },
  },
  {
    id: 'evt-1046',
    timestamp: '2026-09-21 10:38:15 UTC',
    relativeTime: '9m ago',
    severity: 'success',
    type: 'Self-Healing Recovery',
    resource: 'resource-worker',
    resourceId: 'resource-worker',
    description: 'Self-healing retry logic reconnected partition 14 to broker #03 with zero message drops.',
    chips: [
      { label: 'RESOLVED', value: 'HEALED' },
      { label: 'DROPPED', value: '0 msgs' },
      { label: 'DURATION', value: '1.2s' },
    ],
    details: {
      reroute: 'Switched target broker to kafka-broker-03',
      latency: '5.2ms P99 restored',
      nodesInSync: '5 of 5',
    },
    rawJson: {
      eventId: 'evt-1046',
      status: 'RECOVERED',
      reconnectTimeMs: 1240,
    },
  },
  {
    id: 'evt-1045',
    timestamp: '2026-09-21 10:25:00 UTC',
    relativeTime: '22m ago',
    severity: 'info',
    type: 'Health Check Sweep',
    resource: 'res-alt-gw-02',
    resourceId: 'res-alt-gw-02',
    description: 'Automated synthetic probe verified 100% readiness SLA for failover ingress proxy res-alt-gw-02.',
    chips: [
      { label: 'PROBE', value: 'SYNTHETIC SWEEP' },
      { label: 'RESULT', value: '200 OK' },
      { label: 'LATENCY', value: '11.8ms' },
    ],
    details: {
      passed: 120,
      degraded: 0,
      warmupTime: '0ms (Hot Standby)',
      readiness: '100% Ready',
    },
    rawJson: {
      eventId: 'evt-1045',
      probe: 'http_synthetic_check',
      status: 'ALL_PASS',
    },
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  general: {
    projectName: 'Runtime Service Graph Orchestration',
    clusterId: 'cluster-us-east-prod-01',
    environment: 'Production (Multi-AZ)',
    region: 'us-east-1 (N. Virginia)',
    timeStandard: 'UTC (Coordinated Universal Time)',
    displayLocalTime: true,
  },
  runtime: {
    refreshInterval: '5s',
    healthCheckInterval: 5,
    grpcTimeout: 3000,
    retryStrategy: 'Exponential Backoff with Jitter',
    maxRetries: 3,
    baseDelay: '100ms',
    maxDelay: '2000ms',
    circuitBreakerEnabled: true,
  },
  graph: {
    layoutAlgorithm: 'hierarchical',
    showDependencies: true,
    showAlternatives: true,
    packetFlowAnimation: true,
    targetFps: '60 FPS',
  },
  notifications: {
    rules: [
      {
        id: 'rule-01',
        eventTrigger: 'Alternative Promoted to Active',
        description: 'Notify on-call when any failover alternative is promoted to primary traffic carrier.',
        severity: 'CRITICAL',
        escalation: 'PagerDuty On-Call (P1)',
        enabled: true,
      },
      {
        id: 'rule-02',
        eventTrigger: 'Resource State Degraded / Failure',
        description: 'Send warning alert when health probes report > 2% consecutive packet drops.',
        severity: 'WARNING',
        escalation: 'Slack #ops-infrastructure',
        enabled: true,
      },
      {
        id: 'rule-03',
        eventTrigger: 'Self-Healing Circuit Breaker Trip',
        description: 'Log and broadcast event when circuit breaker opens on any service edge.',
        severity: 'INFO',
        escalation: 'Datadog Events Channel',
        enabled: true,
      },
    ],
    slackWebhook: 'https://hooks.slack.com/services/T00/B00/XXXXX (Configured)',
    pagerDutyKey: 'pd-prod-infra-key-8482***',
  },
  api: {
    baseUrl: import.meta.env.VITE_API_BASE_URL || '/api/v1',
    backendStatus: 'connected',
    protocol: 'gRPC-Web / HTTP/2 + JSON fallback',
    rttLatency: '1.8ms',
    lastSync: 'Just now',
    activeChannels: 7,
    memoryBuffer: '4.2 MB / 128 MB',
    certExpiryDays: 84,
    shaValidated: 'sha256:7f8a91b... verified',
  },
};
